### ISSUE TITLE
[User] 권한 추가

### ISSUE THREAD

**Issue by als95** [Co-TLin/MediaService-backend#34]
권한 초기 버전은 앱 관리자, 일반 사용자

권한이 바뀔 경우가 없으므로 JWT에 추가할 것을 권장

**Comment by dongpilYu** [comment]
JWT 안에 어드민, 일반 사용자를 의미하는 필드를 추가하라는 것으로 보이는데 맞을까요?

**Comment by dongpilYu** [comment]
또, 기존 코드가 토큰을 header에 추가하지 않는데, header에 추가하도록 수정하겠습니다.

**Comment by als95** [comment]
> JWT 안에 어드민, 일반 사용자를 의미하는 필드를 추가하라는 것으로 보이는데 맞을까요?

네 맞습니다!

**Comment by als95** [comment]
> 또, 기존 코드가 토큰을 header에 추가하지 않는데, header에 추가하도록 수정하겠습니다.

header는 프론트에서 보내주는 것입니다! 저희는 추가하는 과정이 따로 필요하지 않습니다.

**Comment by dongpilYu** [comment]
클라이언트에서 토큰을 헤더에서 뽑나, 바디에서 뽑나는 크게 상관없을 거 같긴 합니다만 토큰을 발급한 후 클라이언트로 보내줄 때도 header에 추가해주는 것이 더 일반적이지 않은 가에 대한 생각에서 말씀드린 내용이였습니다.
